// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vitxtbotmtxfytusptbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpdHh0Ym90bXR4Znl0dXNwdGJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTg3MjIsImV4cCI6MjA3MTI5NDcyMn0.zb2DJltnhMuBcHjf3Rl1qCSlXVQYdfOCQVQS16Svahw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});